services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - backend
    env_file: ".env"

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - backend
